// DO NOT MODIFY THIS FILE - IT IS AUTO GENERATED BASED ON jsgameviewer/translations/en_us.yml
window.jsgv_en_us = {
  'trunk': 'Game move',
  'comment': 'Comment',
  'result': 'Result',
  'white': 'White',
  'back': 'Back',
  'move_number_after': '',
  'w': 'W',
  'fast_back': 'Fast back',
  'komi': 'Komi',
  'black': 'Black',
  'b': 'B',
  'cancel': 'Cancel',
  'submit': 'OK',
  'jump_to': 'Jump to',
  'whose_turn': 'Next',
  'branch': 'Variation',
  'moves': 'Moves',
  'handicap': 'Handicap',
  'time': 'Time',
  'end': 'Forward to end',
  'forward': 'Forward',
  'prev_comment_or_branch': 'Previous comment or variation',
  'refresh': 'Refresh game/board',
  'fast_forward': 'Fast forward',
  'white_dead': 'W dead',
  'black_dead': 'B dead',
  'play_first': 'Play first',
  'next_comment_or_branch': 'Next comment or variation',
  'show_hide_move_number': 'Show/hide move number',
  'locale': 'en_us',
  'branch_tag': '<Variation>',
  'comment_for': 'Comment for MOVE',
  'place': 'Place',
  'home': 'Back to beginning',
  'open_in_new_window': 'Open in new window',
  'resign': 'Resign',
  'move_number_before': '',
  'rule': 'Rule',
  'jump_to_xx': 'Jump to XX'};
if (window.jsgvTranslations == undefined) window.jsgvTranslations = jsgv_en_us;